// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package index

import (
	mock "github.com/stretchr/testify/mock"
	"github.com/willie68/gowillie68/pkg/measurement"
	"github.com/willie68/schematics2/backend/internal/domain/model"
)

// newMockdocStoreInterface creates a new instance of mockdocStoreInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockdocStoreInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockdocStoreInterface {
	mock := &mockdocStoreInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockdocStoreInterface is an autogenerated mock type for the docStoreInterface type
type mockdocStoreInterface struct {
	mock.Mock
}

type mockdocStoreInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *mockdocStoreInterface) EXPECT() *mockdocStoreInterface_Expecter {
	return &mockdocStoreInterface_Expecter{mock: &_m.Mock}
}

// SearchStore provides a mock function for the type mockdocStoreInterface
func (_mock *mockdocStoreInterface) SearchStore(filter model.Query) model.PagedSearchResult {
	ret := _mock.Called(filter)

	if len(ret) == 0 {
		panic("no return value specified for SearchStore")
	}

	var r0 model.PagedSearchResult
	if returnFunc, ok := ret.Get(0).(func(model.Query) model.PagedSearchResult); ok {
		r0 = returnFunc(filter)
	} else {
		r0 = ret.Get(0).(model.PagedSearchResult)
	}
	return r0
}

// mockdocStoreInterface_SearchStore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchStore'
type mockdocStoreInterface_SearchStore_Call struct {
	*mock.Call
}

// SearchStore is a helper method to define mock.On call
//   - filter model.Query
func (_e *mockdocStoreInterface_Expecter) SearchStore(filter any) *mockdocStoreInterface_SearchStore_Call {
	return &mockdocStoreInterface_SearchStore_Call{Call: _e.mock.On("SearchStore", filter)}
}

func (_c *mockdocStoreInterface_SearchStore_Call) Run(run func(filter model.Query)) *mockdocStoreInterface_SearchStore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 model.Query
		if args[0] != nil {
			arg0 = args[0].(model.Query)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockdocStoreInterface_SearchStore_Call) Return(pagedSearchResult model.PagedSearchResult) *mockdocStoreInterface_SearchStore_Call {
	_c.Call.Return(pagedSearchResult)
	return _c
}

func (_c *mockdocStoreInterface_SearchStore_Call) RunAndReturn(run func(filter model.Query) model.PagedSearchResult) *mockdocStoreInterface_SearchStore_Call {
	_c.Call.Return(run)
	return _c
}

// newMockmeasurementService creates a new instance of mockmeasurementService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockmeasurementService(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockmeasurementService {
	mock := &mockmeasurementService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockmeasurementService is an autogenerated mock type for the measurementService type
type mockmeasurementService struct {
	mock.Mock
}

type mockmeasurementService_Expecter struct {
	mock *mock.Mock
}

func (_m *mockmeasurementService) EXPECT() *mockmeasurementService_Expecter {
	return &mockmeasurementService_Expecter{mock: &_m.Mock}
}

// Start provides a mock function for the type mockmeasurementService
func (_mock *mockmeasurementService) Start(name string) measurement.Monitor {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 measurement.Monitor
	if returnFunc, ok := ret.Get(0).(func(string) measurement.Monitor); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(measurement.Monitor)
		}
	}
	return r0
}

// mockmeasurementService_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type mockmeasurementService_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - name string
func (_e *mockmeasurementService_Expecter) Start(name any) *mockmeasurementService_Start_Call {
	return &mockmeasurementService_Start_Call{Call: _e.mock.On("Start", name)}
}

func (_c *mockmeasurementService_Start_Call) Run(run func(name string)) *mockmeasurementService_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockmeasurementService_Start_Call) Return(monitor measurement.Monitor) *mockmeasurementService_Start_Call {
	_c.Call.Return(monitor)
	return _c
}

func (_c *mockmeasurementService_Start_Call) RunAndReturn(run func(name string) measurement.Monitor) *mockmeasurementService_Start_Call {
	_c.Call.Return(run)
	return _c
}
