// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package backup

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/willie68/gowillie68/pkg/measurement"
	"github.com/willie68/schematics2/backend/internal/domain/model"
)

// newMockstore creates a new instance of mockstore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockstore(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockstore {
	mock := &mockstore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockstore is an autogenerated mock type for the store type
type mockstore struct {
	mock.Mock
}

type mockstore_Expecter struct {
	mock *mock.Mock
}

func (_m *mockstore) EXPECT() *mockstore_Expecter {
	return &mockstore_Expecter{mock: &_m.Mock}
}

// ExportBackup provides a mock function for the type mockstore
func (_mock *mockstore) ExportBackup(ctx context.Context, destPath string) error {
	ret := _mock.Called(ctx, destPath)

	if len(ret) == 0 {
		panic("no return value specified for ExportBackup")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, destPath)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockstore_ExportBackup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExportBackup'
type mockstore_ExportBackup_Call struct {
	*mock.Call
}

// ExportBackup is a helper method to define mock.On call
//   - ctx context.Context
//   - destPath string
func (_e *mockstore_Expecter) ExportBackup(ctx any, destPath any) *mockstore_ExportBackup_Call {
	return &mockstore_ExportBackup_Call{Call: _e.mock.On("ExportBackup", ctx, destPath)}
}

func (_c *mockstore_ExportBackup_Call) Run(run func(ctx context.Context, destPath string)) *mockstore_ExportBackup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockstore_ExportBackup_Call) Return(err error) *mockstore_ExportBackup_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockstore_ExportBackup_Call) RunAndReturn(run func(ctx context.Context, destPath string) error) *mockstore_ExportBackup_Call {
	_c.Call.Return(run)
	return _c
}

// newMockblobStore creates a new instance of mockblobStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockblobStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockblobStore {
	mock := &mockblobStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockblobStore is an autogenerated mock type for the blobStore type
type mockblobStore struct {
	mock.Mock
}

type mockblobStore_Expecter struct {
	mock *mock.Mock
}

func (_m *mockblobStore) EXPECT() *mockblobStore_Expecter {
	return &mockblobStore_Expecter{mock: &_m.Mock}
}

// Load provides a mock function for the type mockblobStore
func (_mock *mockblobStore) Load(ci *model.ContainerInfo) ([]byte, error) {
	ret := _mock.Called(ci)

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*model.ContainerInfo) ([]byte, error)); ok {
		return returnFunc(ci)
	}
	if returnFunc, ok := ret.Get(0).(func(*model.ContainerInfo) []byte); ok {
		r0 = returnFunc(ci)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*model.ContainerInfo) error); ok {
		r1 = returnFunc(ci)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockblobStore_Load_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Load'
type mockblobStore_Load_Call struct {
	*mock.Call
}

// Load is a helper method to define mock.On call
//   - ci *model.ContainerInfo
func (_e *mockblobStore_Expecter) Load(ci any) *mockblobStore_Load_Call {
	return &mockblobStore_Load_Call{Call: _e.mock.On("Load", ci)}
}

func (_c *mockblobStore_Load_Call) Run(run func(ci *model.ContainerInfo)) *mockblobStore_Load_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *model.ContainerInfo
		if args[0] != nil {
			arg0 = args[0].(*model.ContainerInfo)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockblobStore_Load_Call) Return(bytes []byte, err error) *mockblobStore_Load_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *mockblobStore_Load_Call) RunAndReturn(run func(ci *model.ContainerInfo) ([]byte, error)) *mockblobStore_Load_Call {
	_c.Call.Return(run)
	return _c
}

// newMockmeasurementService creates a new instance of mockmeasurementService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockmeasurementService(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockmeasurementService {
	mock := &mockmeasurementService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockmeasurementService is an autogenerated mock type for the measurementService type
type mockmeasurementService struct {
	mock.Mock
}

type mockmeasurementService_Expecter struct {
	mock *mock.Mock
}

func (_m *mockmeasurementService) EXPECT() *mockmeasurementService_Expecter {
	return &mockmeasurementService_Expecter{mock: &_m.Mock}
}

// Start provides a mock function for the type mockmeasurementService
func (_mock *mockmeasurementService) Start(name string) measurement.Monitor {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 measurement.Monitor
	if returnFunc, ok := ret.Get(0).(func(string) measurement.Monitor); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(measurement.Monitor)
		}
	}
	return r0
}

// mockmeasurementService_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type mockmeasurementService_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - name string
func (_e *mockmeasurementService_Expecter) Start(name any) *mockmeasurementService_Start_Call {
	return &mockmeasurementService_Start_Call{Call: _e.mock.On("Start", name)}
}

func (_c *mockmeasurementService_Start_Call) Run(run func(name string)) *mockmeasurementService_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockmeasurementService_Start_Call) Return(monitor measurement.Monitor) *mockmeasurementService_Start_Call {
	_c.Call.Return(monitor)
	return _c
}

func (_c *mockmeasurementService_Start_Call) RunAndReturn(run func(name string) measurement.Monitor) *mockmeasurementService_Start_Call {
	_c.Call.Return(run)
	return _c
}
