// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package backup

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// newMockstore creates a new instance of mockstore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockstore(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockstore {
	mock := &mockstore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockstore is an autogenerated mock type for the store type
type mockstore struct {
	mock.Mock
}

type mockstore_Expecter struct {
	mock *mock.Mock
}

func (_m *mockstore) EXPECT() *mockstore_Expecter {
	return &mockstore_Expecter{mock: &_m.Mock}
}

// ExportBackup provides a mock function for the type mockstore
func (_mock *mockstore) ExportBackup(ctx context.Context, destPath string) error {
	ret := _mock.Called(ctx, destPath)

	if len(ret) == 0 {
		panic("no return value specified for ExportBackup")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, destPath)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockstore_ExportBackup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExportBackup'
type mockstore_ExportBackup_Call struct {
	*mock.Call
}

// ExportBackup is a helper method to define mock.On call
//   - ctx context.Context
//   - destPath string
func (_e *mockstore_Expecter) ExportBackup(ctx any, destPath any) *mockstore_ExportBackup_Call {
	return &mockstore_ExportBackup_Call{Call: _e.mock.On("ExportBackup", ctx, destPath)}
}

func (_c *mockstore_ExportBackup_Call) Run(run func(ctx context.Context, destPath string)) *mockstore_ExportBackup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockstore_ExportBackup_Call) Return(err error) *mockstore_ExportBackup_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockstore_ExportBackup_Call) RunAndReturn(run func(ctx context.Context, destPath string) error) *mockstore_ExportBackup_Call {
	_c.Call.Return(run)
	return _c
}
