// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package hash

import (
	mock "github.com/stretchr/testify/mock"
	"github.com/willie68/schematics2/backend/internal/domain/model"
)

// newMockstorage creates a new instance of mockstorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockstorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockstorage {
	mock := &mockstorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockstorage is an autogenerated mock type for the storage type
type mockstorage struct {
	mock.Mock
}

type mockstorage_Expecter struct {
	mock *mock.Mock
}

func (_m *mockstorage) EXPECT() *mockstorage_Expecter {
	return &mockstorage_Expecter{mock: &_m.Mock}
}

// All provides a mock function for the type mockstorage
func (_mock *mockstorage) All(f func(m model.Document) bool) error {
	ret := _mock.Called(f)

	if len(ret) == 0 {
		panic("no return value specified for All")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(func(m model.Document) bool) error); ok {
		r0 = returnFunc(f)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockstorage_All_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'All'
type mockstorage_All_Call struct {
	*mock.Call
}

// All is a helper method to define mock.On call
//   - f func(m model.Document) bool
func (_e *mockstorage_Expecter) All(f any) *mockstorage_All_Call {
	return &mockstorage_All_Call{Call: _e.mock.On("All", f)}
}

func (_c *mockstorage_All_Call) Run(run func(f func(m model.Document) bool)) *mockstorage_All_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 func(m model.Document) bool
		if args[0] != nil {
			arg0 = args[0].(func(m model.Document) bool)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockstorage_All_Call) Return(err error) *mockstorage_All_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockstorage_All_Call) RunAndReturn(run func(f func(m model.Document) bool) error) *mockstorage_All_Call {
	_c.Call.Return(run)
	return _c
}

// Upsert provides a mock function for the type mockstorage
func (_mock *mockstorage) Upsert(doc model.Document) error {
	ret := _mock.Called(doc)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(model.Document) error); ok {
		r0 = returnFunc(doc)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockstorage_Upsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upsert'
type mockstorage_Upsert_Call struct {
	*mock.Call
}

// Upsert is a helper method to define mock.On call
//   - doc model.Document
func (_e *mockstorage_Expecter) Upsert(doc any) *mockstorage_Upsert_Call {
	return &mockstorage_Upsert_Call{Call: _e.mock.On("Upsert", doc)}
}

func (_c *mockstorage_Upsert_Call) Run(run func(doc model.Document)) *mockstorage_Upsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 model.Document
		if args[0] != nil {
			arg0 = args[0].(model.Document)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockstorage_Upsert_Call) Return(err error) *mockstorage_Upsert_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockstorage_Upsert_Call) RunAndReturn(run func(doc model.Document) error) *mockstorage_Upsert_Call {
	_c.Call.Return(run)
	return _c
}

// newMockblobStore creates a new instance of mockblobStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockblobStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockblobStore {
	mock := &mockblobStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockblobStore is an autogenerated mock type for the blobStore type
type mockblobStore struct {
	mock.Mock
}

type mockblobStore_Expecter struct {
	mock *mock.Mock
}

func (_m *mockblobStore) EXPECT() *mockblobStore_Expecter {
	return &mockblobStore_Expecter{mock: &_m.Mock}
}

// Load provides a mock function for the type mockblobStore
func (_mock *mockblobStore) Load(container *model.ContainerInfo) ([]byte, error) {
	ret := _mock.Called(container)

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*model.ContainerInfo) ([]byte, error)); ok {
		return returnFunc(container)
	}
	if returnFunc, ok := ret.Get(0).(func(*model.ContainerInfo) []byte); ok {
		r0 = returnFunc(container)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*model.ContainerInfo) error); ok {
		r1 = returnFunc(container)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockblobStore_Load_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Load'
type mockblobStore_Load_Call struct {
	*mock.Call
}

// Load is a helper method to define mock.On call
//   - container *model.ContainerInfo
func (_e *mockblobStore_Expecter) Load(container any) *mockblobStore_Load_Call {
	return &mockblobStore_Load_Call{Call: _e.mock.On("Load", container)}
}

func (_c *mockblobStore_Load_Call) Run(run func(container *model.ContainerInfo)) *mockblobStore_Load_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *model.ContainerInfo
		if args[0] != nil {
			arg0 = args[0].(*model.ContainerInfo)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockblobStore_Load_Call) Return(bytes []byte, err error) *mockblobStore_Load_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *mockblobStore_Load_Call) RunAndReturn(run func(container *model.ContainerInfo) ([]byte, error)) *mockblobStore_Load_Call {
	_c.Call.Return(run)
	return _c
}
